### PR TITLE
HQ now counts all the units and broadcasts numbers

### PR DESCRIPTION
**Pull request by brandonsladek**

### CODE REVIEW

**Comment by NickolasLapp** [comment]
Can you please rebase this on origin/master to fix merge conflicts? Then I will automerge

**Comment by brandonsladek** [comment]
How do I do that? Do I just type git push origin master?

**Comment by NickolasLapp** [comment]
http://stackoverflow.com/questions/161813/fix-merge-conflicts-in-git

**Comment by brandonsladek** [comment]
I typed in "git diff" and it showed a couple changes I made in the
BaseRobot file on the getNeededBuilding method. I pushed that file back up
to the origin repo on the UnitCounting branch. I think it should work now.

**Pull request merged**
